classDiagram

    class Team {
        +str id
        +str name
        +obj pokemons

        +search(pokemonName)
        +selectPokemon(pokemon, pokemons)
        +removePokemon(pokemon, pokemons)
    }
